package common;

public enum MessageType {
    CONNECT,
    CONNECTED,
    CREATE_ROOM,
    JOIN_ROOM,
    ADD_BOT,
    UPDATE_MAX_PLAYERS,
    ROOM_UPDATE,
    START_GAME,
    PLAY_CARD,
    DRAW_CARD,
    END_TURN,
    TRIPLE_PEEK_CHOICE,
    ACCEPT_WILD_DRAW_FOUR,
    CHALLENGE_WILD_DRAW_FOUR,
    GAME_STATE,
    TURN_UPDATE,
    TRIPLE_PEEK_OPTIONS,
    PRIVATE_UPDATE,
    PLAYER_STATS_UPDATE,
    INVALID_MOVE,
    GAME_OVER,
    ERROR
}
